# Generated by Django 5.1.7 on 2025-06-17 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('trainer_notes', models.JSONField(blank=True, default=list, null=True)),
                ('meal_timing_notes', models.JSONField(blank=True, default=list, null=True)),
                ('target_calories', models.CharField(max_length=50)),
                ('protein_grams', models.CharField(max_length=50)),
                ('carbs_grams', models.CharField(max_length=50)),
                ('fats_grams', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_of_day', models.CharField(max_length=50)),
                ('calories', models.PositiveIntegerField()),
                ('protein_grams', models.FloatField()),
                ('carbs_grams', models.FloatField()),
                ('fats_grams', models.FloatField()),
                ('foods_description', models.TextField(help_text='List of foods and portions included in the meal')),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='program.nutritionplan')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('protein_grams', models.FloatField(blank=True, help_text='Protein content per serving (optional)', null=True)),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='program.nutritionplan')),
            ],
        ),
    ]
