# Generated by Django 5.1.7 on 2025-06-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_nutritionplan_meal_supplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
