# Generated by Django 5.1.7 on 2025-06-17 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_nutritionplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='nutrition_plan',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='time_of_day',
        ),
        migrations.CreateModel(
            name='MealInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Morning Snack', 'Morning Snack'), ('Lunch', 'Lunch'), ('Afternoon Snack', 'Afternoon Snack'), ('Dinner', 'Dinner'), ('Evening Snack', 'Evening Snack')], max_length=50)),
                ('meal_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.meal')),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_instances', to='program.nutritionplan')),
            ],
        ),
    ]
