# Generated by Django 5.1.7 on 2025-06-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_remove_meal_nutrition_plan_remove_meal_time_of_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='nutrition_plan',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='protein_grams',
        ),
        migrations.CreateModel(
            name='SupplementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('protein_grams', models.FloatField(blank=True, help_text='Protein content per serving (optional)', null=True)),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='program.nutritionplan')),
            ],
        ),
    ]
