# Generated by Django 5.1.7 on 2025-06-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_remove_supplement_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementinstance',
            name='supplement_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='program.supplement'),
            preserve_default=False,
        ),
    ]
