# Generated by Django 5.1.7 on 2025-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_recoveryplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='meal_timing_notes',
            field=models.TextField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='trainer_notes',
            field=models.TextField(blank=True, default=list, null=True),
        ),
    ]
