# Generated by Django 5.1.7 on 2025-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_exercisetemplate_created_at_exercisetemplate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinstance',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
