# Generated by Django 5.1.7 on 2025-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_exerciseinstance_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/images/'),
        ),
    ]
