# Generated by Django 5.1.7 on 2025-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_social_media',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter (X)'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
