# Generated by Django 5.1.7 on 2025-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_is_profile_complete_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
