# Generated by Django 5.1.7 on 2025-03-08 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('brief_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('will_learn', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('purchasers', models.ManyToManyField(blank=True, related_name='purchased_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
