# Generated by Django 5.1.7 on 2025-06-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('training program', 'Training Program'), ('nutrition plan', 'Nutrition Plan'), ('recovery plan', 'Recovery Plan')], default='training program', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('gym', 'Gym'), ('martial_arts', 'Martial Arts')], default='gym', max_length=100),
        ),
    ]
