# Generated by Django 5.1.7 on 2025-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_category_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='will_learn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
